/* Autogenerated file by Willert Simplifier
 * Pleas do not change the content
 *

 *
 *  Virtual table used by Rhapsody's code generator to be able to call operations such as dispatching events, processing  
 *  statecharts, etc. in generated application code from the framework.
 */ 

#ifndef RXF_VirtualTable_H
#define RXF_VirtualTable_H

#include "RXF_Reactive.h"
/*my*/
#include "sm.h"

/** 
*  Type definition for the RXFDispatchEvent function pointer.
*/ 
typedef RXFTakeEventStatus (*RXFDispatchEvent)(void * const void_me, const RXFEventId id);

/** 
*  Type definition for the RXFEntDef function pointer.
*/ 
typedef void (*RXFEntDef)(void * const me);

/** 
*  Type definition for the RXFHandleNotConsumed function pointer.
*/ 
typedef void (*RXFHandleNotConsumed)(RXF_Reactive* const me, RXF_Event* event);

typedef struct RXF_Reactive_Vtbl
{
	/* Pointer to the event handling operation, usually an operation in a class that has a statechart.*/
	RXFDispatchEvent 		dispEventFunc;		/*## attribute dispEventFunc */
	// EventHandler dispEventFunc;

	/* Pointer to the operation, which in Rhapsody init a state machine. */
	RXFEntDef				rootState_entDefFunc;

	/* Pointer to an operation that may handle events which could not be consumes by the state machine. */
	RXFHandleNotConsumed	handleEventNotConsumed;

} RXF_Reactive_Vtbl;

#endif /* RXF_VirtualTable_H */

